### ISSUE TITLE
Current documentation is subpar. Improve this!

### ISSUE THREAD

**Issue by odegnome** [Coder-RG/tocinator#2]
Improve the documentation both in the code and the README. This will help newcomers to get started easily.

**Comment by Tylryan** [comment]
I can help with the documentation. For the code, you are wanting it to be easily read by newcomers. Do you want more doc files for the functions, or are you looking to comment what each line does?

**Comment by odegnome** [comment]
@Tylryan It would be better if we start with documenting the functions.

**Comment by cybertronprime** [comment]
i can help with some issues
